
import { DaySchedule, ItemType } from './types';

// Helper to generate a Google Maps Search Link
const getMapLink = (query: string) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;

export const ITINERARY: DaySchedule[] = [
  {
    id: 'day1',
    dayLabel: 'Day 1',
    dateStr: '2026/02/18',
    location: '越南胡志明 🇻🇳',
    items: [
      {
        id: 'd1-1',
        time: '10:20',
        title: '抵達胡志明市',
        description: '抵達新山一國際機場 (SGN)。',
        type: ItemType.FLIGHT,
      },
      {
        id: 'd1-food1',
        time: '12:00',
        duration: '1小時',
        title: 'Phở Hòa Pasteur',
        description: '胡志明市著名的河粉老店，湯頭鮮甜，牛肉嫩滑，必吃道地美食。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Phở Hòa Pasteur Ho Chi Minh'),
      },
      {
        id: 'd1-2',
        time: '13:00',
        duration: '2小時',
        title: '咖啡公寓 (The Cafe Apartment)',
        description: '由老舊公寓改建而成的文青咖啡聚集地，充滿復古風情，適合拍照打卡。',
        type: ItemType.ACTIVITY,
        link: getMapLink('The Cafe Apartment Ho Chi Minh'),
      },
      {
        id: 'd1-3',
        time: '15:30',
        duration: '2小時',
        title: '濱城市場 (Ben Thanh Market)',
        description: '胡志明市最著名的地標市場，體驗當地美食與手工藝品。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Ben Thanh Market'),
      },
      {
        id: 'd1-food2',
        time: '17:30',
        duration: '30分鐘',
        title: 'Bánh Mì Hùynh Hoa',
        description: '被譽為胡志明市最好吃的法國麵包，餡料豐富扎實。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Bánh Mì Hùynh Hoa'),
      },
      {
        id: 'd1-4',
        time: '18:00',
        duration: '1小時',
        title: '粉紅教堂 (Tan Dinh Church)',
        description: '夢幻的粉紅色外觀哥德式建築，是著名的熱門拍照景點。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Tan Dinh Church'),
      },
      {
        id: 'd1-5',
        time: '22:45',
        title: '轉機前往哥本哈根',
        description: '從胡志明市轉機飛往哥本哈根。',
        type: ItemType.FLIGHT,
      },
    ],
  },
  {
    id: 'day2',
    dayLabel: 'Day 2',
    dateStr: '2026/02/19',
    location: '哥本哈根 🇩🇰 -> 馬爾默 🇸🇪',
    items: [
      {
        id: 'd2-1',
        time: '06:00',
        title: '抵達哥本哈根',
        description: '早上到達哥本哈根機場 (CPH)。',
        type: ItemType.FLIGHT,
      },
      {
        id: 'd2-2',
        time: '07:30',
        duration: '40分鐘',
        title: '搭火車前往馬爾默',
        description: '跨越厄勒海峽大橋前往瑞典馬爾默。',
        type: ItemType.TRAIN,
      },
      {
        id: 'd2-food1',
        time: '08:30',
        duration: '45分鐘',
        title: 'Lilla Kafferosteriet',
        description: '馬爾默迷人的老屋咖啡館，享受瑞典式早餐與肉桂捲。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Lilla Kafferosteriet Malmo'),
      },
      {
        id: 'd2-3',
        time: '09:00',
        duration: '1小時',
        title: '旋轉大樓 (Turning Torso)',
        description: '北歐最高的摩天大樓，獨特的扭轉造型設計，馬爾默的地標。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Turning Torso Malmo'),
      },
      {
        id: 'd2-food2',
        time: '12:00',
        duration: '1小時',
        title: 'Malmö Saluhall (美食廣場)',
        description: '由舊貨運倉庫改建的現代美食廣場，匯集各種瑞典與異國美食。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Malmö Saluhall'),
      },
      {
        id: 'd2-4',
        time: '13:30',
        duration: '2小時',
        title: '馬爾默城堡 (Malmö Castle)',
        description: '斯堪地那維亞現存最古老的文藝復興風格城堡。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Malmö Castle'),
      },
      {
        id: 'd2-5',
        time: '15:00',
        duration: '飛行約2小時',
        title: '飛往特羅姆瑟',
        description: '搭機前往特羅姆瑟。',
        price: '9,003 TWD',
        type: ItemType.FLIGHT,
      },
      {
        id: 'd2-6',
        time: '18:00',
        title: '飯店入住',
        description: '當晚住宿特羅姆瑟市區飯店。',
        link: 'https://secure.booking.com/confirmation.zh-tw.html?aid=304142&label=gen173bo-10CAEoggI46AdIMFgDaOcBiAEBmAEzuAEHyAEM2AED6AEB-AEBiAIBmAIhqAIBuALKs4HIBsACAdICJDMwNzA1YzU5LWVhM2UtNDM1YS1hMDlhLTJkNzVlN2JmYzAyNdgCAeACAQ&auth_key=2Wf9ySa0hkZrTQJM&source=mytrips',
        price: '21,332 TWD',
        type: ItemType.HOTEL,
      },
    ],
  },
  {
    id: 'day3',
    dayLabel: 'Day 3',
    dateStr: '2026/02/20',
    location: '特羅姆瑟 🇳🇴',
    items: [
      {
        id: 'd3-1',
        time: '10:00',
        duration: '1.5小時',
        title: '北極大教堂 (Arctic Cathedral)',
        description: '特羅姆瑟最著名的地標，獨特的三角形建築與彩色玻璃窗。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Arctic Cathedral Tromso'),
      },
      {
        id: 'd3-food1',
        time: '12:00',
        duration: '1小時',
        title: 'Fiskekompaniet',
        description: '港口旁的高級海鮮餐廳，品嚐新鮮的北極帝王蟹與鮮魚料理。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Fiskekompaniet Tromso'),
      },
      {
        id: 'd3-2',
        time: '13:30',
        duration: '2小時',
        title: 'Fjellheisen 纜車',
        description: '搭乘纜車登上斯托斯坦恩山，俯瞰特羅姆瑟全景與峽灣美景。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Fjellheisen Tromso'),
      },
      {
        id: 'd3-3',
        time: '16:00',
        duration: '2小時',
        title: 'Polaria 水族館',
        description: '世界上最北端的水族館，外觀如同倒塌的多米諾骨牌。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Polaria Tromso'),
      },
      {
        id: 'd3-food2',
        time: '18:30',
        duration: '1.5小時',
        title: 'Bardus Bistro',
        description: '結合當地食材與南歐風情的餐酒館，氛圍溫馨。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Bardus Bistro Tromso'),
      },
      {
        id: 'd3-4',
        time: '20:30',
        title: '飯店住宿',
        description: '續住特羅姆瑟。',
        link: 'https://secure.booking.com/confirmation.zh-tw.html?aid=304142&label=gen173bo-10CAEoggI46AdIMFgDaOcBiAEBmAEzuAEHyAEM2AED6AEB-AEBiAIBmAIhqAIBuALKs4HIBsACAdICJDMwNzA1YzU5LWVhM2UtNDM1YS1hMDlhLTJkNzVlN2JmYzAyNdgCAeACAQ&auth_key=2Wf9ySa0hkZrTQJM&source=mytrips',
        price: '21,332 TWD (已包含)',
        type: ItemType.HOTEL,
      },
    ],
  },
  {
    id: 'day4',
    dayLabel: 'Day 4',
    dateStr: '2026/02/21',
    location: '特羅姆瑟 -> 羅浮敦群島 🇳🇴',
    items: [
      {
        id: 'd4-1',
        time: '10:00',
        duration: '1.5小時',
        title: '特羅姆瑟圖書館',
        description: '擁有壯觀玻璃屋頂的現代建築，也是眺望街景的好地方。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Tromso Library'),
      },
      {
        id: 'd4-food1',
        time: '12:00',
        duration: '1小時',
        title: 'Risø Mat & Kaffebar',
        description: '當地人喜愛的咖啡廳，提供美味的三明治與手沖咖啡。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Risø Mat & Kaffebar'),
      },
      {
        id: 'd4-2',
        time: '14:10',
        duration: '飛行約1小時',
        title: '飛往羅浮敦群島',
        description: '搭機前往羅浮敦群島 (Leknes)。',
        price: '9,531 TWD',
        type: ItemType.FLIGHT,
      },
      {
        id: 'd4-3',
        time: '16:00',
        duration: '30分鐘',
        title: '租車取車',
        description: '地點: Lufthavnveien 29, 8370 Leknes, Norway',
        price: '25,502.60 NTD',
        type: ItemType.CAR_RENTAL,
        link: getMapLink('Lufthavnveien 29 8370 Leknes'),
      },
      {
        id: 'd4-4',
        time: '17:00',
        title: '入住 Sakrisøy Gjestegård',
        description: 'Manor House in Sakrisøy - Solbakken anno 1880',
        price: '14,553 TWD',
        type: ItemType.HOTEL,
        link: getMapLink('Sakrisøy Gjestegård'),
      },
      {
        id: 'd4-food2',
        time: '18:00',
        duration: '1.5小時',
        title: 'Anita\'s Sjømat',
        description: '位於 Sakrisøy 的著名海鮮店，必吃魚漢堡與海鮮湯。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Anita\'s Sjømat'),
      },
      {
        id: 'd4-5',
        time: '20:00',
        duration: '1小時',
        title: '前往 Hamnøy Viewpoint',
        description: '羅浮敦最經典的紅色漁屋拍攝點。',
        link: getMapLink('Hamnøy Viewpoint'),
        type: ItemType.ACTIVITY,
      },
    ],
  },
  {
    id: 'day5',
    dayLabel: 'Day 5',
    dateStr: '2026/02/22',
    location: '羅浮敦群島 (南島) 🇳🇴',
    items: [
      {
        id: 'd5-food1',
        time: '08:30',
        duration: '1小時',
        title: 'Bringager Bakeri',
        description: '傳統挪威烘焙坊，肉桂捲與新鮮麵包是早餐首選。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Bakeriet på Å'),
      },
      {
        id: 'd5-1',
        time: '09:30',
        duration: '2.5小時',
        title: '雷訥 (Reine)',
        description: '被譽為挪威最美麗的村莊，壯麗的山峰與漁屋倒影。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Reine Norway'),
      },
      {
        id: 'd5-food2',
        time: '12:30',
        duration: '1小時',
        title: 'Maren Anna',
        description: '位於 Sørvågen 的餐廳，提供精緻的北歐料理與海景。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Maren Anna Sørvågen'),
      },
      {
        id: 'd5-2',
        time: '14:00',
        duration: '2小時',
        title: '奧鎮 (Å i Lofoten)',
        description: '羅浮敦公路的最南端終點，保存完整的漁村博物館。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Å i Lofoten'),
      },
      {
        id: 'd5-3',
        time: '17:00',
        title: '飯店住宿',
        description: 'Sakrisøy Gjestegård - Manor House in Sakrisøy',
        type: ItemType.HOTEL,
        link: getMapLink('Sakrisøy Gjestegård'),
      },
    ],
  },
  {
    id: 'day6',
    dayLabel: 'Day 6',
    dateStr: '2026/02/23',
    location: '羅浮敦群島 (中部) 🇳🇴',
    items: [
      {
        id: 'd6-1',
        time: '10:00',
        duration: '2.5小時',
        title: '努斯峽灣 (Nusfjord)',
        description: '隱藏在峽灣中的古老漁村，是聯合國教科文組織保護的歷史建築群。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Nusfjord'),
      },
      {
        id: 'd6-food1',
        time: '12:30',
        duration: '1小時',
        title: 'Karoline Restaurant',
        description: '位於努斯峽灣內的餐廳，享受寧靜的午餐時光。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Restaurant Karoline Nusfjord'),
      },
      {
        id: 'd6-2',
        time: '14:00',
        duration: '1.5小時',
        title: 'Ramberg Beach',
        description: '北極圈內的白沙灘，海水清澈見底，適合漫步。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Ramberg Beach'),
      },
      {
        id: 'd6-3',
        time: '17:00',
        title: '住宿',
        description: '羅浮敦群島特色漁屋 (Rorbuer)。',
        type: ItemType.HOTEL,
        link: getMapLink('Lofoten Rorbuer'),
      },
    ],
  },
  {
    id: 'day7',
    dayLabel: 'Day 7',
    dateStr: '2026/02/24',
    location: '挪威沿海郵輪 🚢',
    items: [
      {
        id: 'd7-1',
        time: '08:00',
        duration: '全日',
        title: '郵輪之旅 (全日)',
        description: '享受郵輪設施與海上風光，放鬆身心。',
        type: ItemType.ACTIVITY,
      },
      {
        id: 'd7-food1',
        time: '19:00',
        duration: '2小時',
        title: '郵輪晚宴',
        description: '品嚐船上提供的挪威沿海特色自助餐。',
        type: ItemType.ACTIVITY,
      },
      {
        id: 'd7-2',
        time: '20:00',
        title: '夜宿郵輪',
        description: '伴隨海浪聲入眠，期待極光出現。',
        type: ItemType.HOTEL,
      },
    ],
  },
  {
    id: 'day8',
    dayLabel: 'Day 8',
    dateStr: '2026/02/25',
    location: '挪威沿海郵輪 🚢',
    items: [
      {
        id: 'd8-1',
        time: '08:00',
        duration: '全日',
        title: '郵輪之旅 (全日)',
        description: '航行於壯麗的挪威海岸線，欣賞峽灣美景。',
        type: ItemType.ACTIVITY,
      },
      {
        id: 'd8-2',
        time: '20:00',
        title: '夜宿郵輪',
        description: '享受郵輪上的最後一晚。',
        type: ItemType.HOTEL,
      },
    ],
  },
  {
    id: 'day9',
    dayLabel: 'Day 9',
    dateStr: '2026/02/26',
    location: '抵達卑爾根 (Bergen) 🇳🇴',
    items: [
      {
        id: 'd9-1',
        time: '14:30',
        title: '抵達卑爾根',
        description: '郵輪抵達挪威第二大城卑爾根。',
        type: ItemType.TRAIN,
      },
      {
        id: 'd9-2',
        time: '15:30',
        duration: '1.5小時',
        title: '布呂根 (Bryggen)',
        description: '漢薩同盟時期的彩色木屋群，已被列入世界文化遺產。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Bryggen Bergen'),
      },
      {
        id: 'd9-food1',
        time: '17:00',
        duration: '1小時',
        title: 'Bryggeloftet & Stuene',
        description: '卑爾根歷史最悠久的餐廳之一，以鹿肉與傳統挪威菜聞名。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Bryggeloftet & Stuene'),
      },
      {
        id: 'd9-3',
        time: '18:15',
        duration: '1.5小時',
        title: '弗洛伊恩山纜車 (Fløibanen)',
        description: '搭乘纜車登頂，俯瞰卑爾根港灣與城市全景。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Fløibanen'),
      },
      {
        id: 'd9-4',
        time: '20:00',
        duration: '1小時',
        title: '魚市場 (Fish Market)',
        description: '體驗當地海鮮文化，品嚐新鮮的帝王蟹與蝦子。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Fish Market Bergen'),
      },
      {
        id: 'd9-5',
        time: '21:30',
        title: '入住卑爾根機場凱瑞酒店',
        description: 'Clarion Hotel Bergen Airport',
        price: '5,994 TWD',
        link: getMapLink('Clarion Hotel Bergen Airport'),
        type: ItemType.HOTEL,
      },
    ],
  },
  {
    id: 'day10',
    dayLabel: 'Day 10',
    dateStr: '2026/02/27',
    location: '卑爾根 -> 哥本哈根 🇩🇰',
    items: [
      {
        id: 'd10-1',
        time: '10:35',
        duration: '1小時20分',
        title: '飛往哥本哈根',
        description: '從卑爾根搭機前往丹麥哥本哈根。',
        price: '7,794 TWD',
        type: ItemType.FLIGHT,
      },
      {
        id: 'd10-2',
        time: '11:55',
        title: '抵達哥本哈根',
        description: '抵達哥本哈根機場 (CPH)。',
        type: ItemType.FLIGHT,
      },
      {
        id: 'd10-food1',
        time: '13:00',
        duration: '1小時',
        title: 'TorvehallerneKBH (玻璃市場)',
        description: '哥本哈根的美食聖地，必試 Hallernes Smørrebrød 開放式三明治。',
        type: ItemType.ACTIVITY,
        link: getMapLink('TorvehallerneKBH'),
      },
      {
        id: 'd10-3',
        time: '14:30',
        duration: '1小時',
        title: '小美人魚雕像 (The Little Mermaid)',
        description: '哥本哈根最著名的地標，取材自安徒生童話。',
        type: ItemType.ACTIVITY,
        link: getMapLink('The Little Mermaid Copenhagen'),
      },
      {
        id: 'd10-4',
        time: '16:00',
        duration: '30分鐘',
        title: '安徒生銅像',
        description: 'H.C. Andersen by Henry Luckow-Nielsen，位於市政廳旁。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Statue of Hans Christian Andersen Copenhagen'),
      },
      {
        id: 'd10-food2',
        time: '18:00',
        duration: '1.5小時',
        title: 'Restaurant Puk',
        description: '位於市中心的傳統丹麥餐館，提供經典的丹麥肉丸與啤酒。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Restaurant Puk Copenhagen'),
      },
      {
        id: 'd10-5',
        time: '20:00',
        title: '入住哥本哈根機場凱福酒店',
        description: 'Comfort Hotel Copenhagen Airport',
        price: '6,154 TWD',
        link: getMapLink('Comfort Hotel Copenhagen Airport'),
        type: ItemType.HOTEL,
      },
    ],
  },
  {
    id: 'day11',
    dayLabel: 'Day 11',
    dateStr: '2026/02/28',
    location: '哥本哈根 -> 胡志明 ✈️',
    items: [
      {
        id: 'd11-1',
        time: '09:00',
        duration: '航程約13小時',
        title: '飛往胡志明市',
        description: '搭乘航班返回越南胡志明市 (轉機)。',
        type: ItemType.FLIGHT,
      },
      {
        id: 'd11-2',
        time: '12:00',
        title: '機上時光',
        description: '享受機上服務，準備迎接旅程終點。',
        type: ItemType.INFO,
      },
    ],
  },
  {
    id: 'day12',
    dayLabel: 'Day 12',
    dateStr: '2026/03/01',
    location: '胡志明 -> 台北 🇹🇼',
    items: [
      {
        id: 'd12-1',
        time: '04:30',
        title: '抵達胡志明市',
        description: '抵達新山一國際機場，入境進行一日遊。',
        type: ItemType.FLIGHT,
      },
      {
        id: 'd12-food1',
        time: '07:00',
        duration: '1小時',
        title: 'Phở Lệ (錦麗河粉)',
        description: '當地人也喜愛的河粉名店，湯頭濃郁，早晨來一碗暖胃首選。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Phở Lệ Nguyen Trai'),
      },
      {
        id: 'd12-2',
        time: '09:00',
        duration: '1小時',
        title: '西貢中心郵政局',
        description: '由艾菲爾鐵塔設計師設計的法式建築，內部寬敞華麗。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Saigon Central Post Office'),
      },
      {
        id: 'd12-3',
        time: '11:00',
        duration: '1.5小時',
        title: '胡志明市大劇院',
        description: '華麗的法式歌劇院，是市中心的著名地標。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Saigon Opera House'),
      },
      {
        id: 'd12-food2',
        time: '12:30',
        duration: '1小時',
        title: 'Cục Gạch Quán',
        description: '安潔莉娜裘莉也造訪過的越南家常菜餐廳，復古環境非常有氣氛。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Cục Gạch Quán'),
      },
      {
        id: 'd12-4',
        time: '14:00',
        duration: '1.5小時',
        title: '書街 (Nguyen Van Binh)',
        description: '綠意盎然的步行街，兩旁充滿書店與露天咖啡座。',
        type: ItemType.ACTIVITY,
        link: getMapLink('Ho Chi Minh City Book Street'),
      },
      {
        id: 'd12-5',
        time: '16:50',
        title: '飛往台北',
        description: '搭機返回台北，結束美好的旅程。',
        type: ItemType.FLIGHT,
      },
    ],
  },
];
